"""Run Capytaine BEM analysis for the A5S (Attenuator - 5 Segments) and export BEMIO H5.

This script:
  1. Loads the 5 Nemoh-format segment meshes generated by generate_meshes.py
  2. Assembles them into a multi-body FloatingBody in Capytaine
  3. Solves radiation and diffraction BEM problems
  4. Computes impulse response functions (radiation RIRF and excitation IRF)
  5. Writes the result in BEMIO HDF5 format for HydroChrono

Dependencies:
    pip install capytaine numpy h5py scipy

Usage:
    python run_bem.py                 # full BEM solve, writes hydroData/a5s.h5
    python run_bem.py --quick         # reduced resolution for testing
    python run_bem.py --from-nc hydroData/a5s_capytaine.nc  # re-run post-processing only
    python run_bem.py --help          # show all options
"""

from __future__ import annotations

import argparse
import math
import os
import time
from pathlib import Path

import numpy as np
import h5py

try:
    import capytaine as cpt
except ImportError:
    raise ImportError(
        "Capytaine is required: pip install capytaine\n"
        "See https://capytaine.github.io/stable/user_manual/installation.html"
    )


# ---------------------------------------------------------------------------
# A5S layout (must match generate_meshes.py defaults)
# ---------------------------------------------------------------------------
SEGMENT_LENGTH = 36.0
GAP = 0.0
N_SEGMENTS = 5
DIAMETER = 4.0
DRAFT = 1.8
COG_Z_OFFSET = -0.2   # CoG lowered 0.2 m below cylinder axis (ballast)
RHO = 1025.0
G = 9.81
WATER_DEPTH = 250.0


def load_bodies(meshes_dir: Path) -> list[cpt.FloatingBody]:
    """Load Nemoh meshes and configure each body."""
    spacing = SEGMENT_LENGTH + GAP
    bodies = []
    for i in range(N_SEGMENTS):
        cx = SEGMENT_LENGTH / 2.0 + i * spacing
        mesh_path = meshes_dir / f"segment_{i + 1}.nemoh"
        if not mesh_path.exists():
            raise FileNotFoundError(
                f"Mesh not found: {mesh_path}\n"
                "Run generate_meshes.py first."
            )

        mesh = cpt.load_mesh(str(mesh_path), file_format="nemoh")
        body = cpt.FloatingBody(mesh=mesh)
        cog_z = -DRAFT + COG_Z_OFFSET
        body.center_of_mass = np.array([cx, 0.0, cog_z])
        body.rotation_center = np.array([cx, 0.0, -DRAFT])
        body.add_all_rigid_body_dofs()
        body.keep_immersed_part()
        body.name = f"segment_{i + 1}"
        bodies.append(body)
        print(f"  Loaded {body.name}: {body.mesh.nb_faces} panels, center_of_mass={body.center_of_mass}")

    return bodies


def compute_body_hydrostatics(bodies: list[cpt.FloatingBody]) -> list[dict]:
    """Compute hydrostatic properties for each body from its mesh.

    Returns a list of dicts with keys: 'stiffness' (6x6), 'disp_vol', 'cb' (3,).
    """
    results = []
    for body in bodies:
        hs = body.compute_hydrostatics(rho=RHO, g=G)
        C = np.array(hs["hydrostatic_stiffness"])  # 6×6, physical units (N/m, N·m/rad)
        dv = float(hs["disp_volume"])
        cb = np.array(hs["center_of_buoyancy"]).flatten()[:3]
        results.append({"stiffness": C, "disp_vol": dv, "cb": cb})
        print(f"  {body.name}: V_disp={dv:.1f} m³, cb_z={cb[2]:.3f} m, "
              f"C33={C[2,2]:.0f} N/m, C55={C[4,4]:.0f} N·m/rad")
    return results


def solve_bem(
    bodies: list[cpt.FloatingBody],
    freq_range: np.ndarray,
    wave_directions: np.ndarray,
    n_jobs: int = 1,
) -> "xarray.Dataset":
    """Assemble multi-body and solve BEM problems.

    Parameters
    ----------
    n_jobs : int
        Number of parallel workers.  1 = sequential (no joblib dependency).
        -1 = use all available CPU cores.  Requires ``pip install joblib``.
    """
    import xarray as xr

    all_bodies = bodies[0]
    for b in bodies[1:]:
        all_bodies = all_bodies + b
    all_bodies.keep_immersed_part()

    n_problems = len(freq_range) * (len(all_bodies.dofs) + len(wave_directions))
    print(f"\n  Combined body: {all_bodies.mesh.nb_faces} panels, {len(all_bodies.dofs)} DOFs")
    print(f"  Frequency range: {freq_range[0]:.3f} .. {freq_range[-1]:.3f} rad/s ({len(freq_range)} points)")
    print(f"  Wave directions: {np.degrees(wave_directions)} deg")
    print(f"  ~{n_problems} BEM problems to solve")

    if n_jobs != 1:
        try:
            import joblib  # noqa: F401
        except ImportError:
            print("  WARNING: joblib not installed -- falling back to sequential solve.")
            print("           Install with: pip install joblib")
            n_jobs = 1

    if n_jobs == 1:
        print("\n  Solving BEM problems sequentially...")
    elif n_jobs == -1:
        import os as _os
        print(f"\n  Solving BEM problems in parallel (all {_os.cpu_count()} cores)...")
    else:
        print(f"\n  Solving BEM problems in parallel ({n_jobs} workers)...")

    test_matrix = xr.Dataset({
        "omega": freq_range,
        "wave_direction": wave_directions,
        "radiating_dof": list(all_bodies.dofs),
        "water_depth": [WATER_DEPTH],
        "rho": [RHO],
    })

    solver = cpt.BEMSolver()
    t0 = time.time()
    dataset = solver.fill_dataset(test_matrix, all_bodies, n_jobs=n_jobs)
    elapsed = time.time() - t0
    print(f"  BEM solve completed in {elapsed:.1f} s")

    return dataset


def compute_radiation_irf(
    omega: np.ndarray,
    B: np.ndarray,
    t_end: float = 60.0,
    dt: float = 0.05,
) -> tuple[np.ndarray, np.ndarray]:
    """Compute radiation impulse response function K(t) from damping B(omega).

    K(t) = (2/pi) * integral_0^inf B(omega) * cos(omega*t) d_omega

    Parameters
    ----------
    omega : (n_freq,)
    B : (n_freq, ...) - radiation damping, frequency axis **first**
    t_end : max time for IRF
    dt : time step for IRF

    Returns
    -------
    t : (n_t,) time vector
    K : (..., n_t) impulse response function (frequency axis collapsed)
    """
    t = np.arange(0, t_end + dt / 2, dt)
    n_t = len(t)

    trailing = B.shape[1:]
    K = np.zeros(trailing + (n_t,))

    d_omega = np.gradient(omega)
    extra = (slice(None),) + (np.newaxis,) * len(trailing)
    for k in range(n_t):
        w = (np.cos(omega * t[k]) * d_omega)[extra]
        K[..., k] = (2.0 / math.pi) * np.sum(B * w, axis=0)

    return t, K


def compute_excitation_irf(
    omega: np.ndarray,
    F_re: np.ndarray,
    F_im: np.ndarray,
    t_end: float = 60.0,
    dt: float = 0.05,
) -> tuple[np.ndarray, np.ndarray]:
    """Compute excitation impulse response function f(t) from complex excitation force.

    f(t) = (1/2pi) * integral_{-inf}^{inf} F(omega) * exp(i*omega*t) d_omega
         = (1/pi) * integral_0^inf [Re(F)*cos(wt) - Im(F)*sin(wt)] d_omega

    Parameters
    ----------
    omega : (n_freq,)
    F_re : (n_freq, ...) - frequency axis **first**
    F_im : (n_freq, ...) - same layout as F_re
    t_end, dt : time range

    Returns
    -------
    t : (n_t,)
    f : (..., n_t) - frequency axis collapsed
    """
    t = np.arange(-t_end, t_end + dt / 2, dt)
    n_t = len(t)

    trailing = F_re.shape[1:]
    f = np.zeros(trailing + (n_t,))

    d_omega = np.gradient(omega)
    extra = (slice(None),) + (np.newaxis,) * len(trailing)
    for k in range(n_t):
        c = (np.cos(omega * t[k]) * d_omega)[extra]
        s = (np.sin(omega * t[k]) * d_omega)[extra]
        f[..., k] = (1.0 / math.pi) * np.sum(F_re * c - F_im * s, axis=0)

    return t, f


def write_bemio_h5(
    output_path: Path,
    dataset: "xarray.Dataset",
    n_bodies: int,
    body_hydrostatics: list[dict] | None = None,
    irf_t_end: float = 60.0,
    irf_dt: float = 0.05,
) -> None:
    """Convert Capytaine xarray Dataset to BEMIO H5 format for HydroChrono.

    Parameters
    ----------
    body_hydrostatics : list of dict, optional
        Per-body hydrostatic data from ``compute_body_hydrostatics``.
        Each dict has 'stiffness' (6x6), 'disp_vol', 'cb' (3,).

    HydroChrono expects (non-dimensionalised):
        added_mass/inf_freq          -> A / rho                  [6 x 6*N]
        linear_restoring_stiffness   -> C / (rho*g)              [6 x 6]
        radiation RIRF K             -> K / rho                  [6 x 6*N x n_t]
        excitation mag               -> |F_exc| / (rho*g)        [6 x n_dir x n_freq]
        excitation phase             ->  angle(F_exc)            [6 x n_dir x n_freq]
        excitation IRF f             -> f / (rho*g)              [6 x n_dir x n_t]
    """
    rho = float(dataset.attrs.get("rho", RHO))
    g = G
    omega = dataset["omega"].values
    n_freq = len(omega)

    dof_names = list(dataset["radiating_dof"].values)
    n_dof_total = len(dof_names)  # 6 * n_bodies
    dof_per_body = n_dof_total // n_bodies

    wave_dirs = dataset["wave_direction"].values
    n_dir = len(wave_dirs)

    # Capytaine stores frequency as the first axis:
    added_mass_full = dataset["added_mass"].values           # (n_freq, n_dof, n_dof)
    rad_damping_full = dataset["radiation_damping"].values    # (n_freq, n_dof, n_dof)

    Fk = dataset["Froude_Krylov_force"].values               # (n_freq, n_dir, n_dof) complex
    Fd = dataset["diffraction_force"].values                  # (n_freq, n_dir, n_dof) complex
    F_exc = Fk + Fd

    if "hydrostatic_stiffness" in dataset:
        C_full = dataset["hydrostatic_stiffness"].values      # (n_dof, n_dof)
    else:
        C_full = np.zeros((n_dof_total, n_dof_total))

    A_inf = added_mass_full[-1, :, :]                         # (n_dof, n_dof)

    print("  Computing radiation IRF...")
    rirf_t, rirf_K = compute_radiation_irf(omega, rad_damping_full, t_end=irf_t_end, dt=irf_dt)
    n_rirf_t = len(rirf_t)                                    # rirf_K: (n_dof, n_dof, n_t)

    print("  Computing excitation IRF...")
    F_exc_re = np.real(F_exc)                                 # (n_freq, n_dir, n_dof)
    F_exc_im = np.imag(F_exc)
    exc_irf_t, exc_irf_f = compute_excitation_irf(omega, F_exc_re, F_exc_im, t_end=irf_t_end, dt=irf_dt)
    n_exc_t = len(exc_irf_t)                                  # exc_irf_f: (n_dir, n_dof, n_t)

    # HydroChrono's Init1D expects rank-2 datasets (n, 1) for all "1D" arrays,
    # and InitScalar expects (1, 1) for scalars.  Match the standard BEMIO layout.
    def _col(arr):
        """Reshape a 1-D array to a column vector (n, 1) for BEMIO compatibility."""
        return np.asarray(arr).reshape(-1, 1)

    def _scalar(v):
        """Wrap a scalar as a (1, 1) array for BEMIO compatibility."""
        return np.array([[float(v)]])

    print(f"  Writing BEMIO H5 to {output_path}")
    with h5py.File(str(output_path), "w") as f:
        sp = f.create_group("simulation_parameters")
        sp.create_dataset("rho", data=_scalar(rho))
        sp.create_dataset("g", data=_scalar(g))
        if np.isinf(WATER_DEPTH):
            sp.create_dataset("water_depth", data="infinite")
        else:
            sp.create_dataset("water_depth", data=_scalar(WATER_DEPTH))
        sp.create_dataset("w", data=_col(omega))

        for b in range(n_bodies):
            body_name = f"body{b + 1}"
            bg = f.create_group(body_name)

            i0 = b * dof_per_body
            i1 = i0 + dof_per_body

            props = bg.create_group("properties")

            spacing = SEGMENT_LENGTH + GAP
            cx = SEGMENT_LENGTH / 2.0 + b * spacing

            if body_hydrostatics and b < len(body_hydrostatics):
                bhs = body_hydrostatics[b]
                disp_vol = bhs["disp_vol"]
                cb = bhs["cb"]
                C_body = bhs["stiffness"] / (rho * g)
            else:
                disp_vol = 427.6
                cb = np.array([cx, 0.0, -DRAFT * 0.6])
                C_body = C_full[i0:i1, i0:i1] / (rho * g)

            cg = [cx, 0.0, -DRAFT + COG_Z_OFFSET]

            props.create_dataset("disp_vol", data=_scalar(disp_vol))
            props.create_dataset("cg", data=_col(cg))
            props.create_dataset("cb", data=_col(cb))

            hc = bg.create_group("hydro_coeffs")

            hc.create_dataset("linear_restoring_stiffness", data=C_body)

            A_body = A_inf[i0:i1, :] / rho
            am = hc.create_group("added_mass")
            am.create_dataset("inf_freq", data=A_body)

            K_body = rirf_K[i0:i1, :, :] / rho
            rd = hc.create_group("radiation_damping")
            irf_group = rd.create_group("impulse_response_fun")
            irf_group.create_dataset("K", data=K_body)
            irf_group.create_dataset("t", data=_col(rirf_t))

            exc = hc.create_group("excitation")

            # F_exc: (n_freq, n_dir, n_dof) -> body slice (n_freq, n_dir, dof_per_body)
            F_body = F_exc[:, :, i0:i1]
            mag = np.abs(F_body) / (rho * g)
            phase = np.angle(F_body)

            # BEMIO layout: (dof_per_body, n_dir, n_freq)
            exc.create_dataset("mag", data=np.transpose(mag, (2, 1, 0)))
            exc.create_dataset("phase", data=np.transpose(phase, (2, 1, 0)))

            # exc_irf_f: (n_dir, n_dof, n_t) -> body slice (n_dir, dof_per_body, n_t)
            # BEMIO: (dof_per_body, n_dir, n_t)
            f_body = exc_irf_f[:, i0:i1, :] / (rho * g)
            exc_irf_group = exc.create_group("impulse_response_fun")
            exc_irf_group.create_dataset("f", data=np.transpose(f_body, (1, 0, 2)))
            exc_irf_group.create_dataset("t", data=_col(exc_irf_t))

    print(f"  BEMIO H5 written: {output_path}")
    print(f"    Bodies: {n_bodies}, DOF/body: {dof_per_body}")
    print(f"    Frequencies: {n_freq}, Wave directions: {n_dir}")
    print(f"    RIRF time steps: {n_rirf_t}, Excitation IRF time steps: {n_exc_t}")


def _plot_mesh_matplotlib(
    bodies: list[cpt.FloatingBody],
    title: str = "A5S mesh",
) -> None:
    """Render one or more Capytaine bodies with matplotlib (no VTK needed)."""
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection
    import matplotlib.pyplot as plt

    fig = plt.figure(figsize=(16, 6))
    ax = fig.add_subplot(111, projection="3d")

    colors = plt.cm.tab10.colors
    for idx, body in enumerate(bodies):
        verts = body.mesh.vertices
        faces = body.mesh.faces
        color = colors[idx % len(colors)]

        polys = []
        for face in faces:
            poly = [verts[vi] for vi in face if vi < len(verts)]
            if len(poly) >= 3:
                polys.append(poly)

        collection = Poly3DCollection(
            polys, alpha=0.5, facecolor=color,
            edgecolor=(0.2, 0.2, 0.2, 0.3), linewidth=0.3,
        )
        ax.add_collection3d(collection)

    all_verts = np.vstack([b.mesh.vertices for b in bodies])
    margin = 5.0
    x_min, x_max = all_verts[:, 0].min() - margin, all_verts[:, 0].max() + margin
    y_min, y_max = all_verts[:, 1].min() - margin, all_verts[:, 1].max() + margin
    z_min, z_max = all_verts[:, 2].min() - margin, all_verts[:, 2].max() + margin

    ax.set_xlim(x_min, x_max)
    ax.set_ylim(y_min, y_max)
    ax.set_zlim(z_min, z_max)
    ax.set_xlabel("X [m]")
    ax.set_ylabel("Y [m]")
    ax.set_zlabel("Z [m]")
    ax.set_title(title)

    # Draw the waterplane at z = 0
    wp_x = [x_min, x_max, x_max, x_min]
    wp_y = [y_min, y_min, y_max, y_max]
    wp_z = [0, 0, 0, 0]
    wp = Poly3DCollection(
        [list(zip(wp_x, wp_y, wp_z))],
        alpha=0.08, facecolor="cyan", edgecolor="steelblue", linewidth=0.5,
    )
    ax.add_collection3d(wp)

    try:
        ax.set_aspect("equal")
    except NotImplementedError:
        pass

    plt.tight_layout()
    plt.show()


def show_meshes(
    bodies: list[cpt.FloatingBody],
    show_individual: bool = False,
) -> None:
    """Display meshes interactively using matplotlib.

    If *show_individual* is True each segment is shown on its own first,
    then the full 5-body assembly is displayed.
    """
    if show_individual:
        for body in bodies:
            print(f"  Showing {body.name} ({body.mesh.nb_faces} panels) ...")
            _plot_mesh_matplotlib([body], title=f"A5S - {body.name}")

    all_bodies = bodies[0]
    for b in bodies[1:]:
        all_bodies = all_bodies + b
    all_bodies.keep_immersed_part()

    total_panels = all_bodies.mesh.nb_faces
    total_dofs = len(all_bodies.dofs)
    print(f"\n  Showing combined A5S system ({total_panels} panels, {total_dofs} DOFs) ...")
    _plot_mesh_matplotlib(bodies, title=f"A5S - 5 segments ({total_panels} panels, {total_dofs} DOFs)")


def _save_nc(dataset, nc_path: Path) -> None:
    """Save the Capytaine xarray Dataset to NetCDF so the BEM solve can be reused."""
    from capytaine.io.xarray import separate_complex_values
    nc_path.parent.mkdir(parents=True, exist_ok=True)
    ds = separate_complex_values(dataset)
    for coord in ("radiating_dof", "influenced_dof"):
        if coord in ds.coords and hasattr(ds[coord].dtype, "categories"):
            ds[coord] = ds[coord].astype(str)
    ds.to_netcdf(
        str(nc_path),
        encoding={"radiating_dof": {"dtype": "U"}, "influenced_dof": {"dtype": "U"}},
    )
    print(f"  Capytaine NetCDF saved: {nc_path}")


def _load_nc(nc_path: Path):
    """Reload a previously saved Capytaine NetCDF dataset."""
    import xarray as xr
    from capytaine.io.xarray import merge_complex_values
    print(f"  Loading dataset from {nc_path} ...")
    return merge_complex_values(xr.open_dataset(str(nc_path)))


def main() -> None:
    ap = argparse.ArgumentParser(description="Run Capytaine BEM for A5S")
    ap.add_argument("--quick", action="store_true",
                    help="Reduced resolution for quick testing (fewer frequencies/panels)")
    ap.add_argument("--n-freq", type=int, default=None,
                    help="Number of frequency points (default: 200, quick: 30)")
    ap.add_argument("--freq-min", type=float, default=0.05,
                    help="Minimum angular frequency [rad/s]")
    ap.add_argument("--freq-max", type=float, default=3.0,
                    help="Maximum angular frequency [rad/s]")
    ap.add_argument("--irf-t-end", type=float, default=60.0,
                    help="IRF time range [s]")
    ap.add_argument("--irf-dt", type=float, default=0.05,
                    help="IRF time step [s]")
    ap.add_argument("--output", type=Path, default=None,
                    help="Output H5 file path")
    ap.add_argument("--meshes-dir", type=Path, default=None,
                    help="Directory containing .nemoh meshes")
    ap.add_argument("--jobs", "-j", type=int, default=-1,
                    help="Parallel workers for BEM solve (-1 = all cores, 1 = sequential). "
                         "Requires: pip install joblib")
    ap.add_argument("--show", action="store_true",
                    help="Show the assembled 5-body mesh and exit (no BEM solve)")
    ap.add_argument("--show-each", action="store_true",
                    help="Show each segment mesh individually, then the combined system")
    ap.add_argument("--from-nc", type=Path, default=None,
                    help="Skip BEM solve; load a previously saved .nc file and re-run "
                         "post-processing (IRFs + H5 export) only")
    args = ap.parse_args()

    script_dir = Path(__file__).resolve().parent
    meshes_dir = args.meshes_dir or script_dir / "meshes"
    output = args.output or script_dir / "hydroData" / "a5s.h5"
    output.parent.mkdir(parents=True, exist_ok=True)
    nc_path = output.parent / "a5s_capytaine.nc"

    print("=" * 60)
    print("A5S BEM Analysis")
    print("=" * 60)

    # Always load meshes (needed for hydrostatics even with --from-nc)
    print("\nLoading meshes...")
    bodies = load_bodies(meshes_dir)

    if args.show or args.show_each:
        show_meshes(bodies, show_individual=args.show_each)
        return

    print("\nComputing hydrostatics from meshes...")
    body_hydrostatics = compute_body_hydrostatics(bodies)

    if args.from_nc:
        dataset = _load_nc(args.from_nc)
    else:
        n_freq = args.n_freq
        if n_freq is None:
            n_freq = 30 if args.quick else 200

        freq_range = np.linspace(args.freq_min, args.freq_max, n_freq)
        wave_directions = np.array([0.0])

        print("\nRunning BEM...")
        dataset = solve_bem(bodies, freq_range, wave_directions, n_jobs=args.jobs)

        print("\nSaving Capytaine NetCDF (checkpoint)...")
        try:
            _save_nc(dataset, nc_path)
        except Exception as e:
            print(f"  WARNING: NetCDF export failed: {e}")

    print("\nPost-processing and writing H5...")
    write_bemio_h5(output, dataset, N_SEGMENTS,
                   body_hydrostatics=body_hydrostatics,
                   irf_t_end=args.irf_t_end, irf_dt=args.irf_dt)

    print("\nDone.")


if __name__ == "__main__":
    main()
